### ISSUE TITLE
Compile AutoInstall Packages failed.

### ISSUE THREAD

**Issue by kicchip** [dosza/LAMWManager-win#39]
I get compile error when I run lamw_manager
`
Free Pascal Compiler version 3.2.0 [2022/02/21] for i386
Copyright (c) 1993-2020 by Florian Klaempfl and others
(1002) Target OS: Win32 for i386
(3104) Compiling amw_ide_tools.pas
(3104) Compiling amw_ide_menu_items.pas
(3104) Compiling apkbuild.pas
(3104) Compiling gdbmiserverdebuggerlamw.pas
C:\lamw_manager\LAMW\lazandroidmodulewizard\ide_tools\gdbmiserverdebuggerlamw.pas(173,15) Warning: (3057) An inherited method is hidden by "GdbRunCommand:AnsiString;"
C:\lamw_manager\LAMW\lazandroidmodulewizard\ide_tools\gdbmiserverdebuggerlamw.pas(174,31) Hint: (5024) Parameter "InAttach" not used
C:\lamw_manager\LAMW\lazandroidmodulewizard\ide_tools\gdbmiserverdebuggerlamw.pas(228,40) Error: (5000) Identifier not found "dsError"
C:\lamw_manager\LAMW\lazandroidmodulewizard\ide_tools\gdbmiserverdebuggerlamw.pas(244,76) Error: (5000) Identifier not found "dsError"
C:\lamw_manager\LAMW\lazandroidmodulewizard\ide_tools\gdbmiserverdebuggerlamw.pas(245,76) Error: (5000) Identifier not found "dsError"
C:\lamw_manager\LAMW\lazandroidmodulewizard\ide_tools\gdbmiserverdebuggerlamw.pas(246,76) Error: (5000) Identifier not found "dsError"
C:\lamw_manager\LAMW\lazandroidmodulewizard\ide_tools\gdbmiserverdebuggerlamw.pas(307,15) Error: (5000) Identifier not found "dsStop"
gdbmiserverdebuggerlamw.pas(464) Fatal: (10026) There were 5 errors compiling module, stopping
Fatal: (1018) Compilation aborted
Error: C:\lamw_manager\LAMW\LAMW4Windows\fpc\3.2.0\bin\i386-win32\ppc386.exe returned an error exitcode
Error: (lazarus) Compile package amw_ide_tools 0.0: stopped with exit code 1
Error: (lazarus) [TLazPackageGraph.CompileRequiredPackages] "Exit code 1"
Error: (lazarus) Building IDE: Compile AutoInstall Packages failed.
Press any key to continue . . .
`

**Comment by dosza** [comment]
already fixed on 02/22/2022, download the setup and try again
