### ISSUE TITLE
Error: Invalid DLL C:\Windows\system32\common.dll, invalid header size

### ISSUE THREAD

**Issue by smarano** [dosza/LAMWManager-win#45]
Hi, i downloaded and tried to install on my intel CPU, windows 10, 64bit
but i get bvelow error and isntallatoin process stops: 

       Compiling .\oracle\src\oraoci.pp
External command "C:/DEV/Tools/lamw_manager/LAMW/LAMW4Windows/fpc/3.2.0/source/fixes_3_2/compiler/ppc386.exe -Twin32 -FUoracle\units\i386-win32\ -FuC:\DEV\Tools\lamw_manager\LAMW\LAMW4Windows\fpc\3.2.0\source\fixes_3_2\rtl\units\i386-win32\ -Fuoracle\src -Fioracle\src -Ur -Xs -O2 -n -di386 -dRELEASE -XX -CX -Sc -viq oracle\BuildUnit_oracle.pp" failed with exit code 1. Console output:
Target OS: Win32 for i386
Compiling oracle\BuildUnit_oracle.pp
Compiling .\oracle\src\oratypes.pp
Compiling .\oracle\src\ocidyn.pp
Compiling .\oracle\src\oci.pp
Compiling .\oracle\src\oraoci.pp
**oraoci.pp(1437) Error: Invalid DLL C:\Windows\system32\common.dll, invalid header size
oraoci.pp(1437) Fatal: There were 1 errors compiling module, stopping**
Fatal: Compilation aborted

The installer encountered the following error:
Compilation of "BuildUnit_oracle.pp" failed
make[2]: *** [smart] Error 1
make[1]: *** [packages_smart] Error 2
make: *** [build-stamp.i386-win32] Error 2
Build FPC win64 fails

**Comment by dosza** [comment]
This is a windows problem, try run sfc /scannow
